#!/usr/bin/env bash
# gen-reference.sh — generate a version-exact command reference straight from the
# installed coolify CLI, so the agent can rely on it instead of the hand-maintained
# cheatsheet (which drifts across CLI versions). Output lands in references/_generated/
# (gitignored). Re-run after `coolify update`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$SKILL_DIR/references/_generated"

command -v coolify >/dev/null 2>&1 || { echo "❌ coolify CLI not found. Run install-cli.sh first."; exit 1; }

VER="$(coolify version 2>/dev/null | head -n1 || echo unknown)"
VER_DISPLAY="${VER#v}"   # strip optional leading 'v' for display
echo "📚 Generating reference from coolify CLI v${VER_DISPLAY} → references/_generated/"
mkdir -p "$OUT_DIR"

# Markdown docs (one file per command tree) — human + agent readable
if coolify docs markdown -o "$OUT_DIR/markdown" >/dev/null 2>&1; then
  echo "  ✅ markdown   → references/_generated/markdown/"
else
  echo "  ⚠️  'coolify docs markdown' unavailable (older CLI?) — skipped"
fi

# llms.txt / llms-full.txt — purpose-built for AI agents ("Generate llms.txt for AI agents")
if coolify docs llms -o "$OUT_DIR/llms.txt" --full-output "$OUT_DIR/llms-full.txt" >/dev/null 2>&1; then
  echo "  ✅ llms.txt   → references/_generated/llms.txt (+ llms-full.txt)"
else
  echo "  ⚠️  'coolify docs llms' unavailable (older CLI?) — skipped"
fi

# Stamp the version so the agent knows exactly what these files match
printf 'coolify CLI version: %s\ngenerated by: scripts/gen-reference.sh\n' "$VER" > "$OUT_DIR/VERSION.txt"

echo ""
echo "Done. Treat references/_generated/ as the authoritative flag source for THIS CLI version;"
echo "the hand-written references/cli-cheatsheet.md is only a high-frequency quick reference."
